#!/bin/bash
#
# Sends a desktop notification with the latest systemd(1) journal logs for a
# service.

set -eox pipefail

service_name="$1"
unit_dir_path="$2"
invocation_id="$(\
    systemctl show \
        --user \
        --value \
        --property "InvocationID" \
        "${service_name}" \
)"

notify-send \
    --app-name "${service_name}" \
    --icon "${unit_dir_path}/shell-icon.svg" \
    "--" \
    "Command returned non-zero status code" \
    "$(\
        journalctl \
            --user \
            --unit "${service_name}" \
            "_SYSTEMD_INVOCATION_ID=${invocation_id}" \
    )"

exit 0
