#!/bin/bash
#
# Adds apt data sources and preferences fragment files that are formatted
# according to sources.list(5) and apt_preferences(5) respectively.

set -eo pipefail

# constants
PROGNAME="$(basename "$0")"
readonly PROGNAME
readonly ROOT_UID=0

if [ "$(id --user)" != "${ROOT_UID}" ]; then
    printf "%s: %s\n" "${PROGNAME}" "you must run this as root" >&2
    exit 1
fi

install --mode 644 "./apt/docker.sources" "/etc/apt/sources.list.d"
install --mode 644 "./apt/hashicorp.sources" "/etc/apt/sources.list.d"
install --mode 644 "./apt/helm.sources" "/etc/apt/sources.list.d"
install --mode 644 "./apt/papirus-icons.sources" "/etc/apt/sources.list.d"
install --mode 644 "./apt/vscodium.sources" "/etc/apt/sources.list.d"
install --mode 644 "./apt/mozilla.sources" "/etc/apt/sources.list.d"
install --mode 644 "./apt/mozilla.pref" "/etc/apt/preferences.d/mozilla"
install --mode 644 "./apt/fastfetch.sources" "/etc/apt/sources.list.d"
install --mode 644 "./apt/kubectl.sources" "/etc/apt/sources.list.d"
install --mode 644 "./apt/opentofu.sources" "/etc/apt/sources.list.d"
install --mode 644 "./apt/opentofu.gpg" "/etc/apt/keyrings"
install --mode 644 "./apt/opentofu-repo.gpg" "/etc/apt/keyrings"

apt-get update

exit 0
