#!/bin/bash
#
# Applies the GNOME settings (gnome-control-center) and GNOME apps configs that
# are in 'gsettings.txt'.

set -eo pipefail

# constants
PROGNAME="$(basename "$0")"
readonly PROGNAME

apply_gsettings() {
    local gsettings_file_path="$1"
    while read -r schema key value; do
        schemadir_path="/usr/share/glib-2.0/schemas"
        if printf \
            '%s\n' \
            "${schema}" \
            | grep --quiet "org.gnome.shell.extensions" \
        ; then
            if ext_path="$(\
                find \
                    "${HOME}/.local/share/gnome-shell/extensions" \
                    -iname "${schema##*\.}@*" \
                )" \
                && [ "${ext_path}" ] \
            ; then
                schemadir_path="${ext_path}/schemas"
            fi
        fi

        if ! err="$(\
            gsettings \
                --schemadir "${schemadir_path}" \
                set \
                "${schema}" \
                "${key}" \
                "${value}" \
                2>&1 \
        )"; then
            printf \
                "%s: %s %s %s\n" \
                "${PROGNAME}" \
                "${schema}" \
                "${key}" \
                "${err}" \
                >&2
        fi
    done < "${gsettings_file_path}"
}

if ! [ "$(command -v gsettings)" ]; then
    printf "%s: %s\n" "${PROGNAME}" "gsettings cannot be found in the PATH!" >&2
    exit 1
fi

apply_gsettings "./src/gsettings.txt"
if [ -r "./src/gsettings.txt.local" ]; then
    apply_gsettings "./src/gsettings.txt.local"
fi

exit 0
