#!/bin/bash
#
# Installs the systemd.unit(5) files.

set -eo pipefail

mkdir \
    --parents \
    "${HOME}/.config/systemd/user" \
    "$(dirname "${SYSTEMD_SENDMAIL_SCRIPT_PATH}")"

install --mode 644 "./src/systemd/hourly@.timer" "${HOME}/.config/systemd/user"
install \
    --mode 644 \
    "./src/systemd/rclone-amazon-music.service" \
    "${HOME}/.config/systemd/user"

install \
    --mode 644 \
    "./src/systemd/rclone-books.service" \
    "${HOME}/.config/systemd/user"

install \
    --mode 644 \
    "./src/systemd/rclone-google-music.service" \
    "${HOME}/.config/systemd/user"

install \
    --mode 644 \
    "./src/systemd/rclone-wallpapers.service" \
    "${HOME}/.config/systemd/user"

install \
    --mode 644 \
    "./src/systemd/sendmail@.service" \
    "${HOME}/.config/systemd/user"

install \
    --mode 755 \
    "./src/systemd/sendmail" \
    "${SYSTEMD_SENDMAIL_SCRIPT_PATH}"

systemctl daemon-reload --user
systemctl enable --user "hourly@rclone-amazon-music.timer"
systemctl start --user "hourly@rclone-amazon-music.timer"

systemctl enable --user "hourly@rclone-books.timer"
systemctl start --user "hourly@rclone-books.timer"

systemctl enable --user "hourly@rclone-google-music.timer"
systemctl start --user "hourly@rclone-google-music.timer"

systemctl enable --user "hourly@rclone-wallpapers.timer"
systemctl start --user "hourly@rclone-wallpapers.timer"

exit 0
