#!/bin/bash
#
# Installs the systemd.unit(5) files.

set -eo pipefail

mkdir \
    --parents \
    "${HOME}/.config/systemd/user" \
    "${HOME}/.local/libexec/systemd"

install --mode 644 "./src/systemd/hourly@.timer" "${HOME}/.config/systemd/user"
install \
    --mode 644 \
    "./src/systemd/rclone-amazon-music.service" \
    "${HOME}/.config/systemd/user"

install \
    --mode 644 \
    "./src/systemd/rclone-books.service" \
    "${HOME}/.config/systemd/user"

install \
    --mode 644 \
    "./src/systemd/rclone-google-music.service" \
    "${HOME}/.config/systemd/user"

install \
    --mode 644 \
    "./src/systemd/sendmail@.service" \
    "${HOME}/.config/systemd/user"

install --mode 755 "./src/systemd/sendmail" "${HOME}/.local/libexec/systemd"
install \
    --mode 644 \
    "./src/systemd/gnome-schema-sources.path" \
    "${HOME}/.config/systemd/user"

install \
    --mode 644 \
    "./src/systemd/update-compiled-schemas.service" \
    "${HOME}/.config/systemd/user"

install \
    --mode 755 \
    "./src/systemd/update-compiled-schemas" \
    "${HOME}/.local/libexec/systemd"

sudo install \
    --mode 644 \
    "./src/systemd/configure-zswap.service" \
    "/etc/systemd/system"

systemctl daemon-reload --user
systemctl enable --user "hourly@rclone-amazon-music.timer"
systemctl start --user "hourly@rclone-amazon-music.timer"

systemctl enable --user "hourly@rclone-books.timer"
systemctl start --user "hourly@rclone-books.timer"

systemctl enable --user "hourly@rclone-google-music.timer"
systemctl start --user "hourly@rclone-google-music.timer"

systemctl enable --user "gnome-schema-sources.path"
systemctl start --user "gnome-schema-sources.path"

sudo systemctl enable "configure-zswap.service"
sudo systemctl start "configure-zswap.service"

exit 0
