#!/bin/bash
#
# Installs the GNOME Display Manager's (gdm) configs.

set -eo pipefail

# constants
PROGNAME="$(basename "$0")"
readonly PROGNAME

if ! [ "$(command -v pcre2grep)" ]; then
    printf '%s: %s\n' "${PROGNAME}" "pcre2grep cannot be found in the PATH!" >&2
    exit 1
fi

sudo install \
    -D \
    --mode 644 \
    "./src/gdm/greeter.dconf-defaults" \
    "/etc/gdm3/greeter.dconf-defaults" \

if [ -r "./src/gdm/greeter.dconf-defaults.local" ]; then
    schema_group=""
    temp_file_path="$(mktemp)"
    while read -r line; do
        if ! [ "${line}" ]; then
            printf '%s\n' "${line}" >> "${temp_file_path}"
        elif [ "${line:0:1}" = "[" ]; then
            escaped_line="$(\
                sed \
                    's/\[/\\[/; s/\]/\\]/g; s|\/|\\/|g' \
                    <<< "${line}" \
            )"

            if grep \
                --quiet \
                "${escaped_line}" \
                "./src/gdm/greeter.dconf-defaults.local" \
            ; then
                schema_group="$(\
                    pcre2grep \
                        --multiline \
                        "^${escaped_line}(\n\S+)+" \
                        "./src/gdm/greeter.dconf-defaults.local" \
                )"
            fi

            printf '%s\n' "${line}" >> "${temp_file_path}"
        else
            if local_line="$(grep "${line/=*/=}" <<< "${schema_group}")"; then
                printf '%s\n' "${local_line}" >> "${temp_file_path}"
            else
                printf '%s\n' "${line}" >> "${temp_file_path}"
            fi
        fi
    done < "./src/gdm/greeter.dconf-defaults"

    sudo install \
        -D \
        --mode 644 \
        "${temp_file_path}" \
        "/etc/gdm3/greeter.dconf-defaults"
fi

exit 0
