#!/bin/bash
#
# Installs the pam_env.conf(5) environment variables file.

set -eo pipefail

# constants
PROGNAME="$(basename "$0")"
readonly PROGNAME
readonly ROOT_UID=0

if [ "$(id --user)" != "${ROOT_UID}" ]; then
    printf '%s: %s\n' "${PROGNAME}" "you must run this as root" >&2
    exit 1
fi

install \
    --mode 644 \
    "./environment" \
    "/etc/environment"

exit 0
