#!/bin/bash
#
# Installs the systemd.unit(5) files.

set -eo pipefail

install \
    -D \
    --mode 644 \
    --target-directory "${HOME}/.config/systemd/user" \
    "./src/systemd/hourly@.timer" \
    "./src/systemd/rclone-amazon-music.service" \
    "./src/systemd/rclone-books.service" \
    "./src/systemd/rclone-google-music.service" \
    "./src/systemd/gnome-schema-sources.path" \
    "./src/systemd/update-compiled-schemas.service" \
    "./src/systemd/shell-icon.svg" \
    "./src/systemd/notify-send@.service"

install \
    -D \
    --mode 755 \
    --target-directory "${HOME}/.local/libexec/systemd" \
    "./src/systemd/update-compiled-schemas" \
    "./src/systemd/notify-send"

sudo install \
    --mode 644 \
    "./src/systemd/configure-zswap.service" \
    "./src/systemd/shell-icon.svg" \
    "./src/systemd/notify-send-system@.service" \
    "/etc/systemd/system"

sudo install \
    -D \
    --mode 755 \
    --target-directory "/usr/local/libexec/systemd" \
    "./src/systemd/notify-send-system"

systemctl daemon-reload --user
systemctl enable --user "hourly@rclone-amazon-music.timer"
systemctl start --user "hourly@rclone-amazon-music.timer"

systemctl enable --user "hourly@rclone-books.timer"
systemctl start --user "hourly@rclone-books.timer"

systemctl enable --user "hourly@rclone-google-music.timer"
systemctl start --user "hourly@rclone-google-music.timer"

systemctl enable --user "gnome-schema-sources.path"
systemctl start --user "gnome-schema-sources.path"

sudo systemctl enable "configure-zswap.service"
sudo systemctl start "configure-zswap.service"

# run local variant of script
if [ -r "${0}.local" ]; then
    # shellcheck disable=SC2086 # word splitting should never occur here
    ${0}.local
fi

exit 0
