#!/bin/bash
#
# Installs the Firefox web browser configs.

set -eo pipefail

# constants
PROGNAME="$(basename "$0")"
readonly PROGNAME

if ! [ "$(command -v curl)" ]; then
    printf '%s: %s\n' "${PROGNAME}" "curl cannot be found in the PATH!" >&2
    exit 1
fi

if ! [ "$(command -v yq)" ]; then
    printf '%s: %s\n' "${PROGNAME}" "yq cannot be found in the PATH!" >&2
    exit 1
fi

install \
		-D \
		--mode 644 \
		"./src/firefox/1m544c8z.default-release/user.js" \
		"${HOME}/.mozilla/firefox/1m544c8z.default-release/user.js"

install \
		-D \
		--mode 644 \
		"./src/firefox/owjmdw8l.default/.gitignore" \
		"${HOME}/.mozilla/firefox/owjmdw8l.default/.gitignore"

install \
		-D \
		--mode 664 \
		"./src/firefox/installs.ini" \
		"${HOME}/.mozilla/firefox/installs.ini"

install \
		-D \
		--mode 664 \
		"./src/firefox/profiles.ini" \
		"${HOME}/.mozilla/firefox/profiles.ini"

FIREFOX_CERTS_DIR_PATH="/usr/lib/mozilla/certificates"
sudo mkdir --parents "${FIREFOX_CERTS_DIR_PATH}"
if ! sudo curl \
    --silent \
    --proxy "http://${HTTP_PROXY_HOSTNAME}:${HTTP_PROXY_PORT}/" \
    --output "${FIREFOX_CERTS_DIR_PATH}/${HTTP_PROXY_HOSTNAME}.pem" \
    "http://mitm.it/cert/pem"; then
        exit 0
fi

FIREFOX_POLICIES_FILE_PATH="/usr/lib/firefox/distribution/policies.json"
if ! [ -r "${FIREFOX_POLICIES_FILE_PATH}" ]; then
    cat << _EOF_ | sudo tee "${FIREFOX_POLICIES_FILE_PATH}" | yq --prettyPrint --output-format "json"
{
    "policies": {
        "Certificates": {
            "Install": [
                "${HTTP_PROXY_HOSTNAME}.pem"
            ]
        }
    }
}
_EOF_
elif ! [ "$(\
    yq \
        '.["policies"]["Certificates"]["Install"][] | select(. == env(HTTP_PROXY_HOSTNAME) + ".pem")' \
        < "${FIREFOX_POLICIES_FILE_PATH}")" \
    ]; then
        temp_file_path="$(mktemp)"
        yq \
            --prettyPrint \
            --output-format "json" \
            '.["policies"]["Certificates"]["Install"] += env(HTTP_PROXY_HOSTNAME) + ".pem"' \
            < "${FIREFOX_POLICIES_FILE_PATH}" \
            > "${temp_file_path}"
        sudo mv "${temp_file_path}" "${FIREFOX_POLICIES_FILE_PATH}"
fi

exit 0
