#!/bin/bash
#
# Sets icons for files displayed by the Nautilus file manager.

set -eo pipefail

# constants
PROGNAME="$(basename "$0")"
readonly PROGNAME

set_location_icon() {
    local location_path="$1"
    local icon_name="$2"
    if ! gio set \
        "${location_path}" \
        "metadata::custom-icon-name" \
        "${icon_name}" 2> "/dev/null"; then
            printf \
                '%s: %s\n' \
                "${PROGNAME}" \
                "${location_path} no such file or directory" \
                >&2
    fi
}

if ! [ "$(command -v gsettings)" ]; then
    printf '%s: %s\n' "${PROGNAME}" "gsettings cannot be found in the PATH!" >&2
    exit 1
fi

icon_theme="$(gsettings get "org.gnome.desktop.interface" "icon-theme" | tr --delete "'")"
if ! printf '%s' "${icon_theme}" | grep --quiet "Papirus"; then
    printf \
        '%s: %s\n' \
        "${PROGNAME}" \
        "expected a Papirus icon theme to be set" \
        >&2

    exit 1
fi

set_location_icon "${HOME}/git" "folder-git"
set_location_icon "${HOME}/src" "folder-code"
set_location_icon "${HOME}/Steam" "folder-steam"

exit 0
