#!/bin/bash
#
# Syncs the current GNOME settings (gnome-control-center) and GNOME apps configs
# with what's in 'gsettings.txt'.

set -eo pipefail

# constants
PROGNAME="$(basename "$0")"
readonly PROGNAME

if ! [ "$(command -v gsettings)" ]; then
    printf "%s: %s\n" "${PROGNAME}" "gsettings cannot be found in the PATH!" >&2
    exit 1
fi

temp_file_path="$(mktemp)"
exts_path="${HOME}/.local/share/gnome-shell/extensions"
mkdir --parents "${exts_path}"
while read -r schema key value; do
    schemadir_path="/usr/share/glib-2.0/schemas"
    if printf \
        '%s\n' \
        "${schema}" \
        | grep --quiet "org.gnome.shell.extensions" \
    ; then
        if ext_path="$(find "${exts_path}" -name "${schema##*.}@*")" \
            && [ "${ext_path}" ] \
        ; then
            schemadir_path="${ext_path}/schemas"
        fi

        ext_path="${exts_path}/just-perfection-desktop@just-perfection"
        if  [ \
                "${schema}" = "org.gnome.shell.extensions.just-perfection" \
            ] \
            && \
            [ \
                -d "${ext_path}" \
            ] \
        ; then
            schemadir_path="${ext_path}/schemas"
        fi

        ext_path="${exts_path}/appindicatorsupport@rgcjonas.gmail.com"
        if  [ \
                "${schema}" = "org.gnome.shell.extensions.appindicator" \
            ] \
            && \
            [ \
                -d "${ext_path}" \
            ] \
        ; then
            schemadir_path="${ext_path}/schemas"
        fi
    fi

    if ! current_value="$(\
        gsettings \
            --schemadir "${schemadir_path}" \
            get \
            "${schema}" \
            "${key}" \
            2>&1 \
    )"; then
        printf \
            "%s: %s %s %s\n" \
            "${PROGNAME}" \
            "${schema}" \
            "${key}" \
            "${current_value}" \
            >&2
    elif [ "${current_value}" != "${value}" ]; then
        value="${current_value}"
    fi

    printf "%s %s %s\n" "${schema}" "${key}" "${value}" >> "${temp_file_path}"
done < "./src/gsettings.txt"

mv "${temp_file_path}" "./src/gsettings.txt"

exit 0
