#
#
# sysctl.conf(5): sysctl values that override the default kernel parameter
# values.

fs.inotify.max_user_watches = 524288
vm.dirty_background_bytes = 134217728
vm.dirty_bytes = 268435456
vm.page-cluster = 0
vm.swappiness = 180
